spring:
  application:
    name: microservicio-mantenimiento
server:
  port: 8003

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/mantenimiento?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: mysql