services:
  db-mongo:
    container_name: mongodb
    image: mongo:latest
    command:
      - --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: monopatinesdb
    ports:
      - "127.0.0.1:27017:27017"