#spring:
#  application:
#    name: gateway
#  config:
#    import: optional:configserver:http://localhost:8081

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/auth?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  cloud:
#    ADAPTAR A NUESTRO TRABAJO
    gateway:
#      mvc:
#        routes:
#          - id: microestudiante
#            uri: lb://microestudiante
#            predicates:
#              - Path=/api/estudiantes/**
#          - id: microcarrera
#            uri: lb://microcarrera
#            predicates:
#              - Path=/api/carreras/**
#          - id: microinscripcion
#            uri: lb://microinscripcion
#            predicates:
#              - Path=/api/inscripciones/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
