#spring:
#  application:
#    name: microservicio-cuenta
#  main:
#    allow-bean-definition-overriding: true
#  cloud:
#    config:
#      uri: http://localhost:8081
server:
  port: 8005
spring:
  application:
    name: microservicio-cuenta
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/cuenta?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql